version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--quiet',
          'mongodb://localhost:27017/test',
          '--eval',
          'db.runCommand({ ping: 1 })',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
